Upgrade telemetry dependency
appsignal/appsignal-elixir pull request #664
Opened 2021-08-13 10:45 UTC by luismiramirez

Add telemetry 1.0.0 as a compatible dependency.

This should be deployed after https://github.com/appsignal/appsignal-elixir-phoenix/pull/27 to avoid possible conflicts with applications that use telemetry 1.0.0.

2021-08-13 11:22 UTC, tombruijn approved these changes

2021-08-13 11:22 UTC, tombruijn requested changes
Please add changeset :)

2021-08-13 12:59 UTC, tombruijn approved these changes

2021-08-16 10:12 UTC, jeffkreeftmeijer approved these changes

2021-08-16 11:39 UTC, merged