Always return the span from set_attribute/3
appsignal/appsignal-elixir pull request #785
Opened 2022-07-26 13:44 UTC by jeffkreeftmeijer

Previously, the Span.set_attribute/3 function returned nil when
non accepted values (like nil) were passed in the rescue clause.
Instead, this patch makes sure to always return the span.

2022-07-26 15:58 UTC, unflxw approved these changes
Looks good!

While we're here and fixing this, `set_sql` is defined right below it, and it has the same issue (returns nil instead of the span when it doesn't like the value passed to it, which breaks method chaining) -- would you fix that one as well?

Sorry for throwing another chore at you. 😅

2022-07-27 07:36 UTC, luismiramirez approved these changes

2022-07-27 07:42 UTC, tombruijn requested changes

2022-07-27 07:42 UTC, tombruijn commented on test/appsignal/span_test.exs
> +      assert Span.set_attribute(nil, "key", nil) == span
```suggestion
    test "returns span when sending nil values", %{span: span} do
      assert Span.set_attribute(span, "key", nil) == span
```
It didn't test it with a given span so it returned nil, failing the test.

2022-07-27 07:42 UTC, tombruijn commented on .changesets/always-return-the-span-from-span-set_attribute-3.md
> +Always return the Span from Span.set_attribute/3
```suggestion
Always return the Span from Span.set_attribute/3, making it easier to chain this function call.
```

2022-07-27 10:45 UTC, jeffkreeftmeijer commented
Added to set_sql/3. Merging and releasing when green.

2022-07-27 11:10 UTC, tombruijn approved these changes

2022-07-27 11:10 UTC, merged