Add elixir 1.15 to CI
appsignal/appsignal-elixir pull request #851
Opened 2023-06-07 14:07 UTC by jeffkreeftmeijer

Add Elixir 1.15.0-rc.1 to CI, and fix a compilation issue introduced in Elixir 1.15 by using rebar instead of mix to install the ssl_verify_fun dependency for now.

[skip changeset]

2023-06-08 06:14 UTC, tombruijn requested changes
You probably need to rebase to remove some duplicate commits that are already merged on main.

2023-06-09 07:04 UTC, jeffkreeftmeijer commented
This should be good to go, with some more changes and some ignored dialyzer warnings. I've opened https://github.com/appsignal/appsignal-elixir/issues/853 to make sure we get to those later.

2023-06-09 11:20 UTC, tombruijn approved these changes

2023-06-09 11:38 UTC, unflxw approved these changes
Looks good. Thinking about moving the methods that are delegated to `Logger` to something like `Appsignal.Utils.Logger`, just because Appsignal.Utils is a bit of a potpourri. But it's not important.

2023-06-12 12:57 UTC, luismiramirez approved these changes

2023-06-12 13:02 UTC, merged